# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-06-04 08:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_color',
            field=models.CharField(default='#429FDA', max_length=50, verbose_name='课程配色'),
        ),
    ]
