# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-12 09:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_course_course_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='careercourse',
            name='test',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_middle_thumbnall',
            field=models.ImageField(blank=True, default='avatar/default_middle.png', max_length=200, null=True, upload_to='media/avatar/%Y/%m', verbose_name='头像104x104'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_small_thumbnall',
            field=models.ImageField(blank=True, default='avatar/default_small.png', max_length=200, null=True, upload_to='media/avatar/%Y/%m', verbose_name='头像70x70'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='avatar_url',
            field=models.ImageField(blank=True, default='avatar/default_big.png', max_length=200, null=True, upload_to='media/avatar/%Y/%m', verbose_name='头像220x220'),
        ),
    ]
